### Articles

In [1]:
article = []

In [2]:
article.append({'text':'I saw the saw.', 'category':'story'})
article.append({'text':'I saw her standing there.', 'category':'story'})
article.append({'text':'Ofcourse I give her an umbrella.', 'category':'story'})
article.append({'text':'But she give me the saw.', 'category':'story'})
article.append({'text':'I come but she run.', 'category':'story'})

article.append({'text':'The moon is Earth’s closest neighbor.', 'category':'science'})
article.append({'text':'It is the brightest object in the night sky..', 'category':'science'})
article.append({'text':'Learn more about the moon.', 'category':'science'})
article.append({'text':'Scientists have studied the moon for thousands of years.', 'category':'science'})
article.append({'text':'The moon is about 4½ billion years old.', 'category':'science'})

article.append({'text':'People build homes.','category':'animal'})
article.append({'text':'A home keeps us warm and dry.', 'category': 'animal'})
article.append({'text':'It gives us a place to live.','category':'animal'})
article.append({'text':'Animals also build homes.','category':'animal'})
article.append({'text':'Read on to see how.','category':'animal'})

article.append({'text':'This is a human skeleton.','category':'health'})
article.append({'text':'It is made of bones.','category':'health'})
article.append({'text':'Bones shape and support your body.','category':'health'})
article.append({'text':'They also protect your organs.','category':'health'})
article.append({'text':'Calcium helps bones grow strong.','category':'health'})


In [3]:
article

[{'category': 'story', 'text': 'I saw the saw.'},
 {'category': 'story', 'text': 'I saw her standing there.'},
 {'category': 'story', 'text': 'Ofcourse I give her an umbrella.'},
 {'category': 'story', 'text': 'But she give me the saw.'},
 {'category': 'story', 'text': 'I come but she run.'},
 {'category': 'science',
  'text': 'The moon is Earth\xe2\x80\x99s closest neighbor.'},
 {'category': 'science',
  'text': 'It is the brightest object in the night sky..'},
 {'category': 'science', 'text': 'Learn more about the moon.'},
 {'category': 'science',
  'text': 'Scientists have studied the moon for thousands of years.'},
 {'category': 'science',
  'text': 'The moon is about 4\xc2\xbd billion years old.'},
 {'category': 'animal', 'text': 'People build homes.'},
 {'category': 'animal', 'text': 'A home keeps us warm and dry.'},
 {'category': 'animal', 'text': 'It gives us a place to live.'},
 {'category': 'animal', 'text': 'Animals also build homes.'},
 {'category': 'animal', 'text': 'Read 

### Import pandas

In [4]:
import pandas as pd

### Export to DataFrame

In [5]:
news_list = pd.DataFrame.from_dict(article)

In [6]:
news_list

category                                               text
0     story                                     I saw the saw.
1     story                          I saw her standing there.
2     story                   Ofcourse I give her an umbrella.
3     story                           But she give me the saw.
4     story                                I come but she run.
5   science              The moon is Earth’s closest neighbor.
6   science      It is the brightest object in the night sky..
7   science                         Learn more about the moon.
8   science  Scientists have studied the moon for thousands...
9   science            The moon is about 4½ billion years old.
10   animal                                People build homes.
11   animal                      A home keeps us warm and dry.
12   animal                       It gives us a place to live.
13   animal                          Animals also build homes.
14   animal                                Read on to see how.
15   health                          This is a human skeleton.
16   health                               It is made of bones.
17   health                 Bones shape and support your body.
18   health                     They also protect your organs.
19   health                   Calcium helps bones grow strong.

In [ ]:
news_list.head(10)

In [7]:
news_list.category.value_counts()

animal     5
health     5
story      5
science    5
Name: category, dtype: int64

### Convert label to a numerical variable

In [8]:
# convert label to a numerical variable
news_list['label_num'] = news_list.category.map({'story':0, 'science':1, 'animal':2, 'health':3})

In [9]:
news_list

category                                               text  label_num
0     story                                     I saw the saw.          0
1     story                          I saw her standing there.          0
2     story                   Ofcourse I give her an umbrella.          0
3     story                           But she give me the saw.          0
4     story                                I come but she run.          0
5   science              The moon is Earth’s closest neighbor.          1
6   science      It is the brightest object in the night sky..          1
7   science                         Learn more about the moon.          1
8   science  Scientists have studied the moon for thousands...          1
9   science            The moon is about 4½ billion years old.          1
10   animal                                People build homes.          2
11   animal                      A home keeps us warm and dry.          2
12   animal                       It gives us a place to live.          2
13   animal                          Animals also build homes.          2
14   animal                                Read on to see how.          2
15   health                          This is a human skeleton.          3
16   health                               It is made of bones.          3
17   health                 Bones shape and support your body.          3
18   health                     They also protect your organs.          3
19   health                   Calcium helps bones grow strong.          3

### Split into training and testing sets

In [10]:
# split X and y into training and testing sets
from sklearn.cross_validation import train_test_split

/Users/choirudinemcha/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [11]:
X = news_list.text
y = news_list.label_num
print(X.shape)
print(y.shape)

(20,)
(20,)


In [ ]:
train_test_split?

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(18,)
(2,)
(18,)
(2,)


### Feature Extraction

In [ ]:
vect

In [35]:
from sklearn.feature_extraction.text import CountVectorizer

# instantiate the vectorizer
vect = CountVectorizer()

In [ ]:
X_train

In [ ]:
X_test

In [ ]:
y_train

In [36]:
# learn training data vocabulary, then use it to create a document-term matrix
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

# or

# equivalently: combine fit and transform into a single step
# X_train_dtm = vect.fit_transform(X_train)

In [25]:
X_train_dtm

<14x56 sparse matrix of type '<type 'numpy.int64'>'
	with 74 stored elements in Compressed Sparse Row format>

In [ ]:
X_train_dtm

In [37]:
# transform testing data (using fitted vocabulary) into a document-term matrix
X_test_dtm = vect.transform(X_test)
# X_test_dtm

### Classification using NaiveBayes

In [38]:
# import and instantiate a Multinomial Naive Bayes model
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [39]:
# train the model using X_train_dtm (timing it with an IPython "magic command")
%time nb.fit(X_train_dtm, y_train)

CPU times: user 2.23 ms, sys: 1.47 ms, total: 3.7 ms
Wall time: 2.96 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [40]:
# make class predictions for X_test_dtm
y_pred_class = nb.predict(X_test_dtm)

In [ ]:
y_pred_class

In [41]:
# calculate accuracy of class predictions
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

1.0

In [ ]:
y_test

In [ ]:
y_pred_class

In [42]:
# print the confusion matrix
metrics.confusion_matrix(y_test, y_pred_class)

array([[1, 0],
       [0, 1]])

### Clasification test

In [43]:
new_article = ['People build house']
new_article_vect = vect.transform(new_article)
nb.predict(new_article_vect)

# {'animal':0, 'health':1, 'story':2, 'science':3}

array([2])

In [44]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler(with_mean = False)  
scaler.fit(X_train_dtm)

X_training_vector = scaler.transform(X_train_dtm)  
X_test_vector = scaler.transform(X_test_dtm)

### Classification using SVM

In [45]:
from sklearn import svm
from sklearn.metrics import accuracy_score
clf = svm.SVC(kernel='linear')
print("Training Classifier...")
%time clf.fit(X_training_vector, y_train)
print("Predicting...")
prediction = clf.predict(X_test_vector)
print("Prediction:",prediction)
accuracy = accuracy_score(y_test, prediction)
# metrics.accuracy_score(y_test, y_pred_class)
print('Accuracy:', accuracy)

Training Classifier...
CPU times: user 1.08 ms, sys: 436 µs, total: 1.51 ms
Wall time: 1.3 ms
Predicting...
('Prediction:', array([3, 0]))
('Accuracy:', 0.5)


In [ ]:
metrics.accuracy_score(y_test, prediction)

In [ ]:
# print(y_test)
print(prediction)

In [49]:
new_article = ['saw your saw i']
new_article_vect = vect.transform(new_article)
clf.predict(new_article_vect)

# {'news':0, 'finance':1, 'hot':2, 'sport':3, 'travel':4}

array([0])

In [27]:
CountVectorizer?

In [50]:
vect.get_feature_names()

[u'4\xbd',
 u'about',
 u'also',
 u'an',
 u'and',
 u'animals',
 u'billion',
 u'body',
 u'bones',
 u'brightest',
 u'build',
 u'but',
 u'closest',
 u'come',
 u'dry',
 u'earth',
 u'for',
 u'give',
 u'gives',
 u'have',
 u'her',
 u'home',
 u'homes',
 u'how',
 u'human',
 u'in',
 u'is',
 u'it',
 u'keeps',
 u'live',
 u'made',
 u'me',
 u'moon',
 u'neighbor',
 u'night',
 u'object',
 u'of',
 u'ofcourse',
 u'old',
 u'on',
 u'organs',
 u'people',
 u'place',
 u'protect',
 u'read',
 u'run',
 u'saw',
 u'scientists',
 u'see',
 u'shape',
 u'she',
 u'skeleton',
 u'sky',
 u'standing',
 u'studied',
 u'support',
 u'the',
 u'there',
 u'they',
 u'this',
 u'thousands',
 u'to',
 u'umbrella',
 u'us',
 u'warm',
 u'years',
 u'your']

In [53]:
X_train_dtm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])