In [59]:
corpus = ['I saw the saw.',
     'I saw her standing there.',
     'Ofcourse I give her an umbrella.',
     'But she give me the saw.',
     'I come but she run.']

In [44]:
# index_value={i[1]:i[0] for i in vectorizer.vocabulary_.items()}

In [55]:
# fully_indexed = []
# for row in X:
#     fully_indexed.append({index_value[column]:value for (column,value) in zip(row.indices,row.data)})

In [56]:
# fully_indexed

In [57]:
# index_value

In [58]:
# vectorizer.get_feature_names()

In [60]:
# import and instantiate CountVectorizer (with the default parameters)
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [ ]:
# CountVectorizer?

In [61]:
# learn the 'vocabulary' of the training data (occurs in-place)
vect.fit(corpus)

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [62]:
# examine the fitted vocabulary
vect.get_feature_names()

[u'an',
 u'but',
 u'come',
 u'give',
 u'her',
 u'me',
 u'ofcourse',
 u'run',
 u'saw',
 u'she',
 u'standing',
 u'the',
 u'there',
 u'umbrella']

In [63]:
# transform training data into a 'document-term matrix'
simple_train_dtm = vect.transform(corpus)

In [64]:
# convert sparse matrix to a dense matrix
simple_train_dtm.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0]])

In [65]:
import pandas as pd
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_train_dtm.toarray(), columns=vect.get_feature_names())

an  but  come  give  her  me  ofcourse  run  saw  she  standing  the  \
0   0    0     0     0    0   0         0    0    2    0         0    1   
1   0    0     0     0    1   0         0    0    1    0         1    0   
2   1    0     0     1    1   0         1    0    0    0         0    0   
3   0    1     0     1    0   1         0    0    1    1         0    1   
4   0    1     1     0    0   0         0    1    0    1         0    0   

   there  umbrella  
0      0         0  
1      1         0  
2      0         1  
3      0         0  
4      0         0

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

[u'an', u'but', u'come', u'give', u'her', u'me', u'ofcourse', u'run', u'saw', u'she', u'standing', u'the', u'there', u'umbrella']


In [67]:
# index_value={i[1]:i[0] for i in vectorizer.vocabulary_.items()}

# fully_indexed = []
# for row in X:
#     fully_indexed.append({index_value[column]:value for (column,value) in zip(row.indices,row.data)})

In [68]:
pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names())

an       but      come      give       her       me  ofcourse  \
0  0.00000  0.000000  0.000000  0.000000  0.000000  0.00000   0.00000   
1  0.00000  0.000000  0.000000  0.000000  0.458270  0.00000   0.00000   
2  0.48214  0.000000  0.000000  0.388988  0.388988  0.00000   0.48214   
3  0.00000  0.400791  0.000000  0.400791  0.000000  0.49677   0.00000   
4  0.00000  0.444002  0.550329  0.000000  0.000000  0.00000   0.00000   

        run       saw       she  standing       the     there  umbrella  
0  0.000000  0.856606  0.000000  0.000000  0.515971  0.000000   0.00000  
1  0.000000  0.380406  0.000000  0.568014  0.000000  0.568014   0.00000  
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   0.48214  
3  0.000000  0.332693  0.400791  0.000000  0.400791  0.000000   0.00000  
4  0.550329  0.000000  0.444002  0.000000  0.000000  0.000000   0.00000

In [69]:
# example text for model testing
simple_test = ["i give the saw"]

In [70]:
# transform testing data into a document-term matrix (using existing vocabulary)
simple_test_dtm = vect.transform(simple_test)
simple_test_dtm.toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]])

In [71]:
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_test_dtm.toarray(), columns=vect.get_feature_names())

an  but  come  give  her  me  ofcourse  run  saw  she  standing  the  \
0   0    0     0     1    0   0         0    0    1    0         0    1   

   there  umbrella  
0      0         0

In [87]:
from sklearn.cross_validation import train_test_split

In [88]:
corpus = []
corpus.append({'text':'I saw the saw.','sentiment':'0'})
corpus.append({'text':'I saw her standing there.', 'sentiment':'1'})
corpus.append({'text':'Ofcourse I give her an umbrella.','sentiment':'1'})
corpus.append({'text':'But she give me the saw.', 'sentiment':'-1'})
corpus.append({'text':'I come but she run.', 'sentiment':'-1'})

In [89]:
news_corpus = pd.DataFrame.from_dict(corpus)

In [90]:
X = news_corpus.text
y = news_corpus.sentiment
print(X.shape)
print(y.shape)

(5,)
(5,)


In [91]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(4,)
(1,)
(4,)
(1,)


In [92]:
news_corpus

sentiment                              text
0         0                    I saw the saw.
1         1         I saw her standing there.
2         1  Ofcourse I give her an umbrella.
3        -1          But she give me the saw.
4        -1               I come but she run.

In [93]:
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)


In [94]:
X_test_dtm = vect.transform(X_test)

In [95]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [96]:
%time nb.fit(X_train_dtm, y_train)

CPU times: user 1.88 ms, sys: 888 µs, total: 2.77 ms
Wall time: 1.9 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [97]:
y_pred_class = nb.predict(X_test_dtm)

In [98]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.0

In [99]:
metrics.confusion_matrix(y_test, y_pred_class)

array([[0, 0],
       [1, 0]])

In [100]:
X_test

0    I saw the saw.
Name: text, dtype: object

In [101]:
test1 = ['saw your saw i']
new_article_vect = vect.transform(test1)
clf.predict(new_article_vect)

NameError: name 'clf' is not defined